export const USER_REGISTER = 'user_register'
export const USER_LOGIN = 'user_login'
export const USER_DATA = 'user_data'
export const CLEAR_USER_DATA = 'clear_user_data'
export const ADD_CHANNEL = 'add_channel'
export const SET_CURRENT_CHANNEL = 'set_current_channel'